name: MLEnvironment
dependencies:
- python=3.6
- cycler=0.10.0
- kiwisolver=1.1.0
- matplotlib=3.1.3
- numpy=1.18.1
- pandas=0.24.2
- pyparsing=2.4.0
- python-dateutil=2.8.0
- pytz=2019.1
- scipy=1.4.1
- scikit-learn=0.22.1
- seaborn=0.10.0
- six=1.12.0
- joblib=0.13.2
- pytest=5.0.1
- future=0.17.1
- xlrd=1.2.0
- pip
- pip:
  - pprofile==2.0.2
  - jsons==0.8.8
